### ISSUE TITLE
[META] Convert Rancher docs to Docusaurus

### ISSUE THREAD

**Issue by sirredbeard** [rancher/docs#3850]
- [ ] Rancher Desktop
- [ ] Fleet
- [ ] Epinio
- [ ] Harvester
- [ ] Kubewarden
- [ ] NeuVector
- [ ] Elemental
- [ ] Opni
- [ ] Hypper
- [ ] RKE2
- [ ] k3s
- [ ] Rancher

References:
- https://docusaurus.io/
- https://github.com/rancher-sandbox/docs.rancherdesktop.io

**Comment by sirredbeard** [comment]
Notes:
* Some of the projects are hosted on their own sites and published via GitHub Actions. These can be converted in place.
* The main Rancher docs are hosted on legacy Rancher infrastructure and will need to be relocated, in cooperation with EIO, to new infrastructure.

**Comment by sirredbeard** [comment]
Proposed plan:

1. Refine order of project transitions.
2. Approach each engineering team project about making the transition.
3. Work with @catherineluse in UI and @paraglade and @oxr463 in EIO as needed.
4. Develop beta of each site in Docusaurus, test, refine, and then publish.
5. Move on to next project.

**Comment by btat** [comment]
When it's time to convert Rancher (rancher/docs) itself these are some of things we should be addressing:

- Versioning - [Docusaurus docs](https://docusaurus.io/docs/versioning)
    - [ ] Versioned search - [related issue](https://github.com/rancher/docs/issues/3314)
    - [ ] Context/page aware version switching - [related issue](https://github.com/rancher/docs/issues/3837)
- [ ] Last updated - [Docusaurus docs](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-docs#showLastUpdateTime)
- [ ] Synchronized tab choices - [Docusaurus docs](https://docusaurus.io/docs/markdown-features/tabs#syncing-tab-choices)
- [ ] Auto-generated table of contents - [Docusaurus docs](https://docusaurus.io/docs/markdown-features/inline-toc)
- [ ] Page responsiveness (mobile) - [related issue](https://github.com/rancher/docs/issues/3110)
- [ ] Keyboard navigation - [related issue](https://github.com/rancher/docs/issues/2306)
- [ ] Page readability - [related issue](https://github.com/rancher/docs/issues/2307)
- [ ] Edit this page button arrow - [related issue](https://github.com/rancher/docs/issues/2305)
    - Pencil icon used by default.
- [ ] Custom 404 page - [related issue](https://github.com/rancher/docs/issues/2187)
- [ ] Headings say link instead of showing a chain icon - [related issue](https://github.com/rancher/docs/issues/1504)
- [ ] Copy to clipboard for code blocks - [related issue](https://github.com/rancher/docs/issues/488)
    - This will be included by default

**Comment by btat** [comment]
@catherineluse please add anything that I may have missed in [the list above](https://github.com/rancher/docs/issues/3850#issuecomment-1051361338)

**Comment by oxr463** [comment]
> When it's time to convert Rancher (rancher/docs) itself these are some of things we should be addressing

Are these issues EIO should address directly?

**Comment by btat** [comment]
> > When it's time to convert Rancher (rancher/docs) itself these are some of things we should be addressing
> 
> Are these issues EIO should address directly?

I believe most of these should be handled by the docs team, but @sirredbeard can confirm which/if any require EIO assistance.

**Comment by sirredbeard** [comment]
We will need EIO assistance in hosting the new Docusaurus container on new AWS infrastructure (off old Norman) and configuring the `docs.rancher.com` domain. @luthermonson @paraglade

**Comment by oxr463** [comment]
> We will need EIO assistance in hosting the new Docusaurus container on new AWS infrastructure (off old Norman) and configuring the `docs.rancher.com` domain. @luthermonson @paraglade

We're going to bake a new container image? Why not push it to GitHub Pages or an S3 Bucket?

**Comment by sirredbeard** [comment]
We need to have a discussion about the best approach for sustainability and performance, I am open to suggestions from EIO.

**Comment by catherineluse** [comment]
> We will need EIO assistance in hosting the new Docusaurus container on new AWS infrastructure (off old Norman) and configuring the docs.rancher.com domain. 

@divya-mohan0209 who is taking over this work? cc @cnotv

**Comment by divya-mohan0209** [comment]
I do not have their GitHub ID, but shall inquire and get back to you.

**Comment by divya-mohan0209** [comment]
@catherineluse @oxr463 is there right on this thread :)
