### ISSUE TITLE
Broken links #2

### ISSUE THREAD

**Issue by tfiduccia** [rancher/docs#483]
- [X] http://staging.rancher.com/docs/rancher/v2.x/en/admin-settings/authentication/azure-ad/#configure-azure-ad-in-rancher - "Configure Azure AD in Rancher" does not go anywhere
- fixed with https://github.com/rancher/docs/pull/486

- [x] https://graph.windows.net/ - Pretty sure this is wrong site?
- fixed with #519 

- [x] http://staging.rancher.com/docs/rancher/v2.x/en/admin-settings/pod-security-policies/ - You have 2 - Run As User Policy links (and I think the first is supposed to something about Volumes, because it goes to Volumes & Files section?)
![image](https://user-images.githubusercontent.com/11514927/42852819-85531ee4-89e7-11e8-94ba-eab92af0bbca.png)

- fixed #519

- [X] http://staging.rancher.com/docs/rancher/v2.x/en/cluster-provisioning/hosted-kubernetes-clusters/gke/#create-a-gke-service-account - "Create a Service Account" doesn't go anywhere
- fixed with https://github.com/rancher/docs/pull/486

- [X] http://staging.rancher.com/rancher/v2.x/en/cluster-provisioning/rke-clusters/options/cloud-providers/ - 404 - fixed with https://github.com/rancher/docs/pull/486

- [X] http://staging.rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/options/ - this page is empty. - fixed with https://github.com/rancher/docs/pull/484

- [X] http://staging.rancher.com/docs/rancher/v2.x/en/cluster-provisioning/custom-clusters/ - this page is empty. - fixed with https://github.com/rancher/docs/pull/480/files

- [ ] http://staging.rancher.com/docs/rancher/v2.x/en/cluster-provisioning/custom-clusters/ - this page is empty. **duplicate? **

- [X] http://staging.rancher.com/rancher/v2.x/en/kubernetes-in-rancher/editing-clusters/ - 404 - fixed with https://github.com/rancher/docs/pull/484

- [X] http://staging.rancher.com/docs/rancher/v2.x/en/kubernetes-in-rancher/#registries - Certificates, ConfigMaps, Secrets & Registries links go nowhere. - fixed with https://github.com/rancher/docs/pull/484

- [X] http://staging.rancher.com/docs/rancher/v2.x/en/kubernetes-in-rancher/projects-namespaces/ - 404 page - fixed with https://github.com/rancher/docs/pull/484

- [X] http://staging.rancher.com/docs/rancher/v2.x/en/kubernetes-in-rancher/kubectl - "Accessing Clusters with kubectl CLI and a kubeconfig File" link goes nowhere - fixed with https://github.com/rancher/docs/pull/484

- [X] http://staging.rancher.com/docs/rancher/v2.x/en/kubernetes-in-rancher/projects-and-namespaces/editing-projects/ - "Existing Cluster: Adding a Pod Security Policy" link goes nowhere
- fixed with https://github.com/rancher/docs/pull/484

- [X] http://staging.rancher.com/docs/rancher/v2.x/en/kubernetes-in-rancher/load-balancers-and-ingress/ - page is empty - added with #495

- [X] http://staging.rancher.com/docs/rancher/v2.x/en/kubernetes-in-rancher/projects/add-ssl-certificates/ - 404 page - fixed with https://github.com/rancher/docs/pull/484

- [X] http://staging.rancher.com/docs/rancher/v2.x/en/kubernetes-in-rancher/volumes-and-storage/provisioning-storage - 404 page - fixed with https://github.com/rancher/docs/pull/484

- [x] http://staging.rancher.com/docs/rancher/v2.x/en/kubernetes-in-rancher/add-a-secret - 404 page - fixed with https://github.com/rancher/docs/pull/484

- [X] http://staging.rancher.com/docs/rancher/v2.x/en/catalog/#chart-types - "notable advantages" link goes nowhere  - fixed with https://github.com/rancher/docs/pull/484

- [X] http://staging.rancher.com/docs/rancher/v2.x/en/tools/ - page is empty - added with #502

- [X] http://staging.rancher.com/docs/rancher/v2.x/en/catalogs-and-charts/#rancher-chart-structure - 404 page  - fixed with https://github.com/rancher/docs/pull/484

- [X] http://staging.rancher.com/docs/rancher/v2.x/en/catalogs-and-charts/catalogs - 404 page  - fixed with https://github.com/rancher/docs/pull/484

- [X] http://staging.rancher.com/docs/rancher/v2.x/en/user-settings/node-templates/ - page is empty - new issue - https://github.com/rancher/docs/issues/510

- [X] http://staging.rancher.com/docs/rancher/v2.x/en/user-settings/preferences/ - page is empty - new issue - https://github.com/rancher/docs/issues/511
